# Nextcloud Apache with Mariadb

services:
  db:
    image: mariadb:lts
    container_name: nextcloud-mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    user: 1000:1000
    volumes:
      #- db:/var/lib/mysql
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - nextcloud

  app:
    container_name: nextcloud-app
    image: nextcloud:stable
    restart: unless-stopped
    user: 1000:1000
    depends_on: 
      - db
    ports:
      - 80:80
      - 443:443
      - 3478:3478
      - 8080:8080
      - 8443:8443
    volumes:
      - html:/var/www/html/
      - data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
    env_file:
      - .env
    networks:
      - nextcloud

networks:
  nextcloud:
    external: true
    name: nextcloud


volumes:
  db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1,async
      device: ":/srv/docker/nextcloud/db"
  html:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1,async
      device: ":/srv/docker/nextcloud/html"
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.localdomain.lan,rw,vers=4.1,async
      device: ":/srv/docker/nextcloud/data"
