# Nextcloud Apache with Mariadb

services:
  db:
    image: mariadb:lts
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    user: 1000:1000
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - nextcloud

  app:
    image: nextcloud:stable
    user: 1000:1000
      #ports:
      #- 80:80
      #- 443:443
      #- 3478:3478
      #- 8080:8080
      #- 8443:8443
    volumes:
      - html:/var/www/html/
      - data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
    env_file:
      - .env
    networks:
      - nextcloud

networks:
  nextcloud:
    driver: overlay
    name: nextcloud
    attachable: true

volumes:
  db:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.tyler-clark.com,rw,vers=4.1
      device: ":/srv/docker/nextcloud-docker/db"
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.tyler-clark.com,rw,vers=4.1
      device: ":/srv/docker/nextcloud-docker/data"
  html:
    driver: local
    driver_opts:
      type: nfs
      o: addr=fileserver.tyler-clark.com,rw,vers=4.1
      device: ":/srv/docker/nextcloud-docker/html"
