# Nextcloud Apache with Mariadb
volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:lts
    container_name: nextcloud-mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      #- db:/var/lib/mysql
      - ./db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - nextcloud

  app:
    container_name: nextcloud-app
    image: nextcloud:stable
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 9001:80
    volumes:
      - ./html:/var/www/html/
      - ./data:/var/www/html/data
    environment:
      - MYSQL_HOST=db
    env_file:
      - .env
    networks:
      - nextcloud

networks:
  nextcloud:
    external: true
    name: nextcloud
